# Generated by Django 5.1 on 2026-03-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_operacao_usd_brl_operacao_moeda_operacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacao',
            name='moeda_operacao',
        ),
        migrations.AlterField(
            model_name='operacao',
            name='moeda',
            field=models.CharField(choices=[('BRL', 'Real Brasileiro (BRL)'), ('USD', 'Dólar Americano (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'Libra Esterlina (GBP)'), ('JPY', 'Iene Japonês (JPY)'), ('CAD', 'Dólar Canadense (CAD)'), ('AUD', 'Dólar Australiano (AUD)'), ('CHF', 'Franco Suíço (CHF)'), ('CNY', 'Yuan Chinês (CNY)'), ('SEK', 'Coroa Sueca (SEK)')], default='BRL', max_length=3, verbose_name='Moeda'),
        ),
    ]
