# Generated by Django 5.1 on 2026-03-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_operacao_moeda_operacao_alter_operacao_moeda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacao',
            name='ativo',
        ),
        migrations.AddField(
            model_name='operacao',
            name='nome_ativo',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nome do Ativo'),
        ),
    ]
