# Generated by Django 5.1 on 2026-03-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_operacao_ativo_operacao_nome_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='compra_venda',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], default='COMPRA', max_length=10),
        ),
    ]
