# Generated by Django 5.1 on 2026-03-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_operacao_compra_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='compra_venda',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], default='COMPRA', max_length=10, verbose_name='Negociação'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='mercado',
            field=models.CharField(choices=[('AVISTA', 'À vista'), ('FRACIONARIO', 'Mercado fracionário')], default='FRACIONARIO', max_length=20),
        ),
    ]
