# Generated by Django 5.1 on 2026-03-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_operacao_compra_venda_alter_operacao_mercado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='mercado',
            field=models.CharField(choices=[('AVISTA', 'À vista'), ('FRACIONARIO', 'Fracionário')], default='AVISTA', max_length=20),
        ),
    ]
