# Generated by Django 5.1 on 2026-03-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_operacao_mercado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('SMALL', 'Smallcap'), ('MID', 'Midcap'), ('LARGE', 'Largecap')], max_length=10),
        ),
    ]
