# Generated by Django 5.1 on 2026-03-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_ativo_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='corretora',
            field=models.CharField(choices=[('XP', 'XP Investimentos'), ('RICO', 'Rico Investimentos'), ('CLEAR', 'Clear Corretora'), ('MODALMAIS', 'Modalmais'), ('TORO', 'Toro Investimentos'), ('EASYNVEST', 'Easynvest'), ('GUIDE', 'Guide Investimentos'), ('ORAMA', 'Órama'), ('SANTANDER', 'Santander Corretora'), ('BRADESCO', 'Bradesco Corretora'), ('ITAU', 'Itaú Corretora'), ('BTG', 'BTG Pactual'), ('BB', 'Banco do Brasil'), ('CAIXA', 'Caixa Econômica Federal'), ('SAFRA', 'Safra Corretora'), ('MORGAN', 'Morgan Stanley'), ('GOLDMAN', 'Goldman Sachs'), ('CREDIT', 'Credit Suisse'), ('JPMORGAN', 'JP Morgan'), ('MERRILL', 'Merrill Lynch')], max_length=20),
        ),
    ]
