# Generated by Django 5.1 on 2026-03-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_operacao_corretora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='corretora',
            field=models.CharField(choices=[('XP', 'XP Investimentos'), ('RICO', 'Rico Investimentos'), ('CLEAR', 'Clear Corretora'), ('MODALMAIS', 'Modalmais'), ('TORO', 'Toro Investimentos'), ('EASYNVEST', 'Easynvest'), ('GUIDE', 'Guide Investimentos'), ('ORAMA', 'Órama'), ('SANTANDER', 'Santander Corretora'), ('BRADESCO', 'Bradesco Corretora'), ('ITAU', 'Itaú Corretora'), ('BTG', 'BTG Pactual'), ('BB', 'Banco do Brasil'), ('CAIXA', 'Caixa Econômica Federal'), ('SAFRA', 'Safra Corretora'), ('AVENUE', 'Avenue Securities'), ('FIDELITY', 'Fidelity Investments'), ('SCHWAB', 'Charles Schwab'), ('TDAMERITRADE', 'TD Ameritrade'), ('ETRADE', 'E*TRADE'), ('VANGUARD', 'Vanguard'), ('MERRILL', 'Merrill Lynch'), ('WELLSFARGO', 'Wells Fargo'), ('JPMORGAN', 'JPMorgan Chase'), ('GOLDMAN', 'Goldman Sachs'), ('MORGAN', 'Morgan Stanley'), ('CREDIT', 'Credit Suisse')], default='XP', max_length=20),
        ),
    ]
