# Generated by Django 5.1 on 2026-03-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_operacao_corretora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacao',
            name='ticker',
        ),
        migrations.AddField(
            model_name='operacao',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Descrição'),
        ),
    ]
