# Generated by Django 5.1 on 2026-03-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_operacao_ticker_operacao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='tipo',
            field=models.CharField(choices=[('ACAO', 'Acao'), ('FII', 'FII'), ('STOCK', 'Stock'), ('REIT', 'REIT'), ('ETF', 'ETF'), ('TITULO_PUBLICO', 'Titulo Publico'), ('TITULO_PRIVADO', 'Titulo Privado'), ('CDB', 'CDB')], default='ACAO', max_length=20),
        ),
    ]
