# Generated by Django 5.1 on 2026-03-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_operacao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacao',
            name='descricao',
        ),
    ]
