# Generated by Django 5.1 on 2026-03-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_operacao_corretora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='moeda',
            field=models.CharField(choices=[('BRL', 'Real Brasileiro (BRL)'), ('USD', 'Dólar Americano (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'Libra Esterlina (GBP)'), ('JPY', 'Iene Japonês (JPY)'), ('CAD', 'Dólar Canadense (CAD)'), ('AUD', 'Dólar Australiano (AUD)'), ('CHF', 'Franco Suíço (CHF)'), ('CNY', 'Yuan Chinês (CNY)'), ('SEK', 'Coroa Sueca (SEK)'), ('ARS', 'Peso Argentino (ARS)'), ('CLP', 'Peso Chileno (CLP)'), ('MXN', 'Peso Mexicano (MXN)'), ('PEN', 'Sol Peruano (PEN)'), ('COP', 'Peso Colombiano (COP)'), ('UYU', 'Peso Uruguaio (UYU)'), ('PYG', 'Guarani Paraguaio (PYG)'), ('BOB', 'Boliviano (BOB)'), ('VEF', 'Bolívar Venezuelano (VEF)'), ('KRW', 'Won Sul-Coreano (KRW)'), ('INR', 'Rupia Indiana (INR)'), ('RUB', 'Rublo Russo (RUB)'), ('ZAR', 'Rand Sul-Africano (ZAR)'), ('TRY', 'Lira Turca (TRY)'), ('SGD', 'Dólar de Singapura (SGD)'), ('HKD', 'Dólar de Hong Kong (HKD)'), ('NZD', 'Dólar Neozelandês (NZD)'), ('NOK', 'Coroa Norueguesa (NOK)'), ('DKK', 'Coroa Dinamarquesa (DKK)'), ('PLN', 'Złoty Polonês (PLN)'), ('CZK', 'Coroa Tcheca (CZK)'), ('HUF', 'Forint Húngaro (HUF)'), ('ILS', 'Shekel Israelense (ILS)'), ('EGP', 'Libra Egípcia (EGP)')], default='BRL', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Preço unitário'),
        ),
        migrations.AlterField(
            model_name='provento',
            name='tipo',
            field=models.CharField(choices=[('ACAO', 'Ações'), ('ACAO_EUA', 'Ações EUA'), ('BDR', 'BDR'), ('DESPESAS', 'Despesas'), ('DIREITO_SUBSCRICAO', 'Direito de subscrição'), ('DOLAR_FUTURO', 'Dólar Futuro'), ('ETF', 'ETF'), ('ETF_RENDA_FIXA', 'ETF Renda Fixa'), ('ETF_USA', 'ETF USA'), ('FI_AGRO', 'FI Agro'), ('FII', 'Fundo Imobiliário'), ('FUNDOS_ISENTOS', 'Fundos Isentos'), ('FUTUROS_OUTROS', 'Futuros Outros'), ('INDICE_FUTURO', 'Índice Futuro'), ('JUROS_FUTUROS', 'Juros Futuros'), ('MUTUAL_FUNDS_USA', 'Mutual Funds USA'), ('OPCOES', 'Opções'), ('OPCOES_EUA', 'Opções EUA'), ('OPCOES_FLEXIVEIS', 'Opções Flexíveis'), ('OURO_BOLSA', 'Ouro na bolsa'), ('REIT', 'REIT'), ('RENDA_FIXA_EUA', 'Renda Fixa EUA'), ('TERMO', 'Termo'), ('FUNDO_ACOES', 'Fundo de ações'), ('FUNDO_MULTIMERCADO', 'Fundo Multimercado'), ('FUNDO', 'Fundo'), ('TITULO_PUBLICO', 'Título Público'), ('DEBENTURE', 'Debênture'), ('CDB', 'CDB'), ('RDB', 'RDB'), ('LCI', 'LCI'), ('LCA', 'LCA'), ('CRI', 'CRI'), ('CRA', 'CRA'), ('STOCK', 'Stock'), ('TITULO_PRIVADO', 'Título Privado')], max_length=20),
        ),
    ]
